basePath: /api/v1
info:
  contact: {}
  description: API for Service
  title: Backend Service
  version: "1.0"
paths: {}
securityDefinitions:
  Bearer:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
